### ISSUE TITLE
Nombre de stream suivis

### ISSUE THREAD

**Issue by SWGAKamui** [Jack3113/StreamersOnline#18]
Est-il normal que le nombre de personne total que je surveille sur twitch n'est pas le même sur streamOn ?
Exemple, je surveille 14 personnes, j'en vois 11 sur streamOn.

**Comment by HackJack-101** [comment]
Tu peux faire une capture d'écran de ta popup ?

**Comment by SWGAKamui** [comment]
![image](https://cloud.githubusercontent.com/assets/12644051/15055966/a1d38334-130f-11e6-98a7-3b432ebf9883.png)
![image](https://cloud.githubusercontent.com/assets/12644051/15055994/c19ac588-130f-11e6-93fc-34f625d3e0ab.png)

**Comment by HackJack-101** [comment]
Tu peux me copier-coller la liste des streams dans les options ? Je pense savoir

**Comment by SWGAKamui** [comment]
http://www.twitch.tv/mistermv
http://www.twitch.tv/gaminglive_powerplay
http://www.twitch.tv/gaminglive_inderetro
http://www.twitch.tv/sandbagtv
http://www.twitch.tv/yamaturga
http://www.twitch.tv/swga_bx/
http://www.twitch.tv/swga_maho/
http://www.twitch.tv/truetekkensurvivor360
http://www.twitch.tv/max_damagetekken
http://www.twitch.tv/tekkencrash_en
http://www.twitch.tv/playhearthstone
http://www.twitch.tv/yamato_fr

**Comment by SWGAKamui** [comment]
Ok, j'ai compris, ça a pas synchronisé ma liste. Je pensais que c'était le cas.
Le nombre est bon maintenant.

**Comment by HackJack-101** [comment]
Je n'ai pas encore mis en place cette option (elle ne va pas tarder).

**Comment by SWGAKamui** [comment]
Ok!
Sorry pour la petite peur !
